### ISSUE TITLE
Type 'T' does not satisfy the constraint 'object'

### ISSUE THREAD

**Issue by alansmithnbs** [RobinBuschmann/sequelize-typescript#368]
When upgrading to TypeScript 2.7.2 I am seeing the error:

`node_modules/@types/sequelize/node_modules/@types/lodash/index.d.ts(12651,53): error TS2344: Type 'T' does not satisfy the constraint 'object'.`

I'm using:
 - sequelize-typescript:  v0.6.4
 - sequelize: v4.37.8
 - typescript: v2.7.2

Issue seems to be with lodash typings - (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23375)

Has anyone managed to get sequelize-typescript working with Typescript 2.7?

**Comment by RobinBuschmann** [comment]
Hey @alansmithnbs, thanks for reporting. Unfortunately I couldn't reproduce the issue. Can you provide a full example? Feel free to use the repo I've just created for this issue https://github.com/RobinBuschmann/st-368.
