### ISSUE TITLE
class decorator when called as an expression

### ISSUE THREAD

**Issue by spearmootz** [RobinBuschmann/sequelize-typescript#593]
had 0.6.6 started presenting this issue 
https://github.com/RobinBuschmann/sequelize-typescript/issues/583

then i updated to 0.6.9
and i get the following error.

```
src/models/Version.ts:11:1 - error TS1238: Unable to resolve signature of class
decorator when called as an expression.
  Cannot invoke an expression whose type lacks a call signature. Type 'void' has
 no compatible call signatures.

11 @Table({
   ~~~~~~~~
12   timestamps: true
   ~~~~~~~~~~~~~~~~~~
13 })
   ~~
```

im using tsc 3.3.4000.

**Comment by RobinBuschmann** [comment]
@spearmootz This is bug. Thanks for reporting

**Comment by RobinBuschmann** [comment]
I'm closing this. @spearmootz If you have further questions or doesn't see this issue resolved, just reopen it.

**Comment by rccoder** [comment]
> @spearmootz This is because `sequelize@5` doesn't work with `sequelize-typescript@0.6.X`. For `sequelize@5` you have to use `sequelize-typescript@canary`

@RobinBuschmann  Thx，solved my problem
