### ISSUE TITLE
typescript building errors

### ISSUE THREAD

**Issue by fareshan** [RobinBuschmann/sequelize-typescript#623]
**Versions**
- sequelize: 5.8.6
- sequelize-typescript: 1.0.0-beta.3
- typescript: 2.7.2

**I'm submitting a ...** 
[x] bug report
[ ] feature request

**Actual behavior:**
After upgrading sequelize and sequelize-typescript, I get these errors when I build the code:
```
node_modules/sequelize-typescript/dist/associations/belongs-to-many/belongs-to-many-options.d.ts(5,48): error TS1005: ';' expected.
node_modules/sequelize-typescript/dist/associations/belongs-to-many/belongs-to-many-options.d.ts(6,1): error TS1128: Declaration or statement expected.
node_modules/sequelize-typescript/dist/associations/through/through-options.d.ts(4,42): error TS1005: ';' expected.
node_modules/sequelize-typescript/dist/associations/through/through-options.d.ts(5,1): error TS1128: Declaration or statement expected.
node_modules/sequelize-typescript/dist/scopes/scope-find-options.d.ts(4,36): error TS1005: ';' expected.
node_modules/sequelize-typescript/dist/scopes/scope-find-options.d.ts(4,76): error TS1005: ')' expected.
node_modules/sequelize-typescript/dist/scopes/scope-find-options.d.ts(4,135): error TS1005: ';' expected.
node_modules/sequelize-typescript/dist/scopes/scope-find-options.d.ts(5,1): error TS1128: Declaration or statement expected.
node_modules/sequelize-typescript/dist/scopes/scope-find-options.d.ts(7,33): error TS1005: ';' expected.
node_modules/sequelize-typescript/dist/scopes/scope-find-options.d.ts(8,18): error TS1005: ',' expected.
node_modules/sequelize-typescript/dist/scopes/scope-find-options.d.ts(10,1): error TS1128: Declaration or statement expected.
```

**Comment by fareshan** [comment]
the issue happens in versions 0.6.9+ (it works in 0.6.8)

**Comment by RobinBuschmann** [comment]
Hey @fareshan thanks for bringing this up. `sequelize-typescript@1.0.0-beta.3` requires at least `typescript@3.0`. While `0.6.9` needs `typescript@2.9.1`. (With `sequelize-typescript@1.0.0` it will follow semver - so no breaking changes for minor versions any more)

**Comment by RobinBuschmann** [comment]
@fareshan So it solved your issue, right? Can we close this now?

**Comment by fareshan** [comment]
Thanks a lot @RobinBuschmann . I close it.
