### ISSUE TITLE
Cannot transpile with TypeScript 3.0.1

### ISSUE THREAD

**Issue by vekexasia** [RobinBuschmann/sequelize-typescript#428]
Hello,

I've been trying to update my proj to typescript 3.0.1 but unfortunately sequelize-typescript does not transpile correctly due to this:

```
node_modules/sequelize-typescript/lib/utils/types.d.ts:9:16 - error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

9     [P in Diff<keyof T, K>]: T[P];
                 ~~~~~~~
```

**Comment by azmtb** [comment]
In your `tsconfig.json` -

```
"strictNullChecks": false,
```

or add `!` to the variable

I believe.

**Comment by RobinBuschmann** [comment]
Hey thanks for reporting. With `sequelize-typescript@0.6.6-beta.1` it should already work. Please give it a try!

**Comment by natesilva** [comment]
Is beta 0.6.6 ready? We’d like to get this fix but don’t want to reference a beta version in our package.json.

**Comment by RobinBuschmann** [comment]
Hey @natesilva its released now under `0.6.6`

**Comment by natesilva** [comment]
Thank you!

**Comment by rokerkony** [comment]
hey,
we have now similar problem after upgrade from 0.6.5 to 0.6.6:
```
node_modules/sequelize-typescript/lib/utils/types.d.ts:4:11 - error TS2322: Type 'U' is not assignable to type 'string'.
  Type 'PropertyKey' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

4     [P in U]: never;
```

versions:
`typescript: 2.8.3`
`sequelize: 4.38.0`
`sequelize-typescript: 0.6.6`

**Comment by RobinBuschmann** [comment]
@rokerkony Thanks for reporting. The actual issue is this https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#keyof-now-includes-string-number-and-symbol-keys

Since `0.6.6` sequelize-typescript supports typescript 2.9. These changes https://github.com/RobinBuschmann/sequelize-typescript/pull/380/files#diff-4212381977d6ae7d5f3204c974608a4eL1 made it possible, but breaks typescript 2.8. For now I cannot think of a solution which makes typescript 2.8 and typescript 2.9/3.0 happy at the same time. Any ideas?

**Comment by RobinBuschmann** [comment]
Close issue due to former issue is resolved
