### ISSUE TITLE
@canary version does not work well with sequelize v5

### ISSUE THREAD

**Issue by Acathur** [RobinBuschmann/sequelize-typescript#539]
errors
```
node_modules/sequelize-typescript/dist/associations/belongs-to-many/belongs-to-many-association-options.d.ts:1:10 - error TS2305: Module'"../node_modules/sequelize/types"' has no exported member 'AssociationOptionsManyToMany'.

1 import { AssociationForeignKeyOptions, AssociationOptionsManyToMany } from "sequelize";
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...

node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize.d.ts:8:3 - error TS2305: Module '"../node_modules/sequelize/types"' has no exported member 'DataTypeBigInt'.

8   DataTypeBigInt,
    ~~~~~~~~~~~~~~
...

node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize.d.ts:289:21 - error TS2304: Cannot find name 'col'.

289   col(col: string): col;
                        ~~~
...
...
```
dependencies
```
{
    "sequelize": "^5.0.0-beta.16",
    "sequelize-typescript": "^1.0.0-alpha.7"
}
```

**Comment by RobinBuschmann** [comment]
Hey @Acathur, this is because sequelize@5 provides its own typings. these typings are loaded prior to the typings from `@types/sequelize`, which are the ones sequelize-typescript relies on. There is already an issue for this: #529

**Comment by Acathur** [comment]
@RobinBuschmann I got it, so what I can do is wait for the new release?

**Comment by RobinBuschmann** [comment]
@Acathur Exactly, but I'm already working on it

**Comment by RobinBuschmann** [comment]
Released `sequelize-typescript@1.0.0-alpha.8`/`sequelize-typescript@canary` now, which should work with `sequelize@5.0.0-beta.16`

**Comment by Acathur** [comment]
cool!!!

**Comment by RobinBuschmann** [comment]
If you found any specific issue with the latest canary release, just open a new issue!
